name: UltimateBingo
version: '${project.version}'
main: io.shantek.UltimateBingo
api-version: '1.20'

# Esto establece PlaceholderAPI como una dependencia opcional para tu plugin.
softdepend: [PlaceholderAPI]

commands:
  bingo:
    description: Abre tus cartas de bingo actuales. Usa start o stop para iniciar o detener el bingo. Configura opciones con settings

permissions:
  shantek.ultimatebingo.start:
    description: Permite a los jugadores iniciar juegos usando el comando start
    default: op

  shantek.ultimatebingo.stop:
    description: Permite a los jugadores detener juegos usando el comando stop
    default: op

  shantek.ultimatebingo.settings:
    description: Permite a los jugadores añadir o quitar ítems del juego
    default: op

  shantek.ultimatebingo.signs:
    description: Permite a los jugadores configurar e iniciar juegos con letreros dentro del juego.
    default: op

